# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: NodeTool@0
  inputs:
    versionSpec: '10.15.1'
  displayName: 'Install Node.js'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: Sonarcloud
    organization: 'trekking-for-charity'
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 't4c_org'
    cliProjectVersion: '$(Build.BuildNumber)'
    extraProperties: |
     sonar.sources=src
     sonar.tests=src
     sonar.test.inclusions=src/**/*.spec.ts
     sonar.coverage.exclusions=src/scripts/infrastructure/app-start.ts
     sonar.exclusions=src/**/*.spec.ts
     sonar.typescript.lcov.reportPaths=coverage/lcov.info
- script: npm install    
  displayName: 'install'

- script: npm run font:install
  displayName: 'install font'

- script: npm run build:partial
  displayName: 'build for partials release'

- script: npm run build:main
  displayName: 'build for main release'

- script: npm run test:coverage
  displayName: 'tests'
  
- task: PublishTestResults@2
  displayName: 'Publish Test Results coverage/xunit-report.xml'
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'coverage/junit-report.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from coverage/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'coverage/cobertura-coverage.xml'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'